// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANTfqzEMLaNaCQYuh9iI4oJJ_5SiP725I',
    appId: '1:1018592035498:web:d40bdb03285a748d0386d3',
    messagingSenderId: '1018592035498',
    projectId: 'mutooni-a0a26',
    authDomain: 'mutooni-a0a26.firebaseapp.com',
    storageBucket: 'mutooni-a0a26.appspot.com',
    measurementId: 'G-70YKGB8D48',
  );


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_hpsA7aVqDtLwDyB75WphRJc-r0RxKbM',
    appId: '1:1018592035498:android:e6929cf4f866a84a0386d3',
    messagingSenderId: '1018592035498',
    projectId: 'mutooni-a0a26',
    storageBucket: 'mutooni-a0a26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8X7VcQ2Z6Y4Y4Y4Y4Y4Y4Y4Y4Y4Y4Y4Y',
    appId: '1:123456789012:ios:abcdefghijklmnopqrstuv',
    messagingSenderId: '123456789012',
    projectId: 'mutooni-erp',
    storageBucket: 'mutooni-erp.appspot.com',
    iosClientId: '123456789012-abcdefghijklmnopqrstuvwxyz123456.apps.googleusercontent.com',
    iosBundleId: 'com.mutooni.erp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8X7VcQ2Z6Y4Y4Y4Y4Y4Y4Y4Y4Y4Y4Y4Y',
    appId: '1:123456789012:ios:abcdefghijklmnopqrstuv',
    messagingSenderId: '123456789012',
    projectId: 'mutooni-erp',
    storageBucket: 'mutooni-erp.appspot.com',
    iosClientId: '123456789012-abcdefghijklmnopqrstuvwxyz123456.apps.googleusercontent.com',
    iosBundleId: 'com.mutooni.erp',
  );
}